# Generated by Django 3.0.3 on 2020-04-02 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('murr_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='murrcard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='murr_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
