# Generated by Django 3.0.3 on 2020-08-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('likes_count', models.IntegerField()),
                ('url', models.TextField()),
                ('search_phrase', models.TextField()),
            ],
        ),
    ]
