# Generated by Django 3.0.3 on 2020-03-12 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorDataForMurrCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_for_murr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EditorImageForMurrCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('murr_editor_image', models.ImageField(max_length=255, null=True, upload_to='editor_image_for_murr_card/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='MurrCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('cover', models.ImageField(blank=True, upload_to='murren_pics')),
                ('description', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
