# Generated by Django 3.0.3 on 2020-03-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murr_card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MurrCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='murr_cover/%Y/%m/%d/')),
            ],
        ),
    ]
