# Generated by Django 3.0.8 on 2020-09-06 04:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('murr_card', '0002_murrcard_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='murrcard',
            name='disliked_murrens',
            field=models.ManyToManyField(related_name='disliked_murrcards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='murrcard',
            name='liked_murrens',
            field=models.ManyToManyField(related_name='liked_murrcards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='murrcard',
            name='rating',
            field=models.IntegerField(blank=True, default=0, verbose_name='Рейтинг'),
        ),
    ]
