# Generated by Django 3.0.3 on 2020-03-28 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('murr_card', '0002_murrcard_owner'),
        ('murr_card', '0002_murrcover'),
    ]

    operations = [
    ]
