# Generated by Django 3.0.3 on 2020-03-28 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('murr_card', '0003_merge_20200328_0434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MurrCover',
        ),
    ]
