# Generated by Django 3.0.8 on 2020-09-14 17:12

from django.db import migrations
import django_enum_choices.choice_builders
import django_enum_choices.fields
import murr_card.models


class Migration(migrations.Migration):

    dependencies = [
        ('murr_card', '0003_auto_20200906_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='murrcard',
            name='status',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('release', 'release'), ('draft', 'draft'), ('moderation', 'moderation')], default=murr_card.models.MurrCardStatus['DRAFT'], enum_class=murr_card.models.MurrCardStatus, max_length=10),
        ),
    ]
