# Generated by Django 3.0.3 on 2020-06-27 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('murr_card', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
