# Generated by Django 3.0.8 on 2020-09-15 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('murr_card', '0004_murrcard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murrcard',
            name='disliked_murrens',
            field=models.ManyToManyField(blank=True, related_name='disliked_murrcards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='murrcard',
            name='liked_murrens',
            field=models.ManyToManyField(blank=True, related_name='liked_murrcards', to=settings.AUTH_USER_MODEL),
        ),
    ]
