# Generated by Django 3.0.8 on 2020-09-01 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(blank=True, max_length=4, null=True, verbose_name='Тип оценки')),
                ('object_id', models.PositiveIntegerField(verbose_name='Идентификатор объекта')),
                ('object_type', models.CharField(max_length=255, verbose_name='Тип объекта')),
                ('murren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Муррен')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
    ]
