# Generated by Django 3.0.8 on 2020-09-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murr_rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_type',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Тип оценки'),
        ),
    ]
