# Generated by Django 3.0.8 on 2020-09-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('murr_rating', '0002_auto_20200905_1129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
