# Generated by Django 3.0.8 on 2020-09-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murren', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='murren',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as banned. ', verbose_name='banned'),
        ),
    ]
