name: murr_devops_name

on:
  push:
    branches: [ develop ]
    
    
jobs:
  my_first_job:
    runs-on: ubuntu-latest   
    steps:
      - name: TEST SSH CONNECTION
        uses: appleboy/ssh-action@master
        with:
          host: 35.228.83.205
          username: murrengan_test
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~
            mkdir delete1

# jobs:
#   my_first_job:
#     runs-on: ubuntu-latest
#     services:
#       redis:
#         image: redis

#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.x'
          
#       - name: Run Redis in docker
#         run: docker run -d -p 127.0.0.1:6379:6379 redis
        
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
#       - name: Test with pytest
#         run: |
#           pytest
