name: murr_devops

on:
  pull_request:
    branches: [ develop ]

jobs:
  test_on_pull_request_to_develop:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Run Redis in docker
        run: docker run -d -p 127.0.0.1:6379:6379 redis
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest
