name: murr_devops

on:
  push:
    branches: [ master ]

jobs:
  run_test_and_update_murr_back:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run redis i ndocker for test
        run: docker run -d -p 127.0.0.1:6379:6379 redis

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pytest

      - name: Rebuild docker-compose on server
        uses: appleboy/ssh-action@master
        with:
          host: 35.228.83.205
          username: murrengan_test
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/murr_back
            git pull origin master
            docker-compose -f docker-compose-prod.yml down
            docker-compose -f docker-compose-prod.yml up --build -d
